#!/usr/bin/env python3
"""Bundle the plugin into single self-contained .qml files.

Development keeps the logic in strings.js and analyse.js, which the .qml files
import. For installation it is nicer to hand over one file per plugin.

A QML object body only accepts property and function declarations — pasting the
modules' top-level `var COLOR = …`, `var _divCache = …` etc. straight in makes the
component fail to compile. So both modules go inside one IIFE assigned to a single
property, where ordinary JavaScript is legal:

    property var lib: (function () {
        …strings.js…      var S = { COLOR: COLOR, lookup: lookup, … };
        …analyse.js…      var A = { analyse: analyse, … };     // can call S.foo
        return { S: S, A: A };
    })()

and the QML body's `S.foo` / `A.foo` become `lib.S.foo` / `lib.A.foo`.

The property name MUST start with a lowercase letter. QML reserves capitalised
identifiers for types, so `property var Lib` compiles to "Component is not ready"
with no further explanation — that cost an afternoon, hence this note.

Output: dist/PlayabilityChecker.qml (live, the one to install) and
        dist/PlayabilityChecker-oneshot.qml (dialog fallback).
Both are build products and are git-ignored — run this script to get them back.
"""
import os, re

HERE = os.path.dirname(os.path.abspath(__file__))
PLUGIN = HERE                       # this script sits in the plugin folder
DIST = os.path.join(HERE, 'dist')
MODULES = [('S', 'strings.js'), ('A', 'analyse.js')]
LIB = 'lib'
# source file  ->  name to publish it under in dist/
QMLS = [('orchestration-checker-live.qml', 'PlayabilityChecker.qml'),
        ('orchestration-checker.qml',      'PlayabilityChecker-oneshot.qml')]


def module_source(path):
    src = open(path).read()
    src = re.sub(r'^\s*\.pragma\s+library\s*$', '', src, flags=re.M)
    src = re.sub(r'^\s*\.import\s+.*$', '', src, flags=re.M)
    return src.strip()


def exported_names(src):
    """Top-level declarations — the module's public surface."""
    names = re.findall(r'^function\s+([A-Za-z_]\w*)\s*\(', src, flags=re.M)
    names += re.findall(r'^var\s+([A-Za-z_]\w*)\s*=', src, flags=re.M)
    seen, out = set(), []
    for n in names:
        if n not in seen:
            seen.add(n)
            out.append(n)
    return out


def indent(text, spaces):
    pad = ' ' * spaces
    return '\n'.join(pad + line if line.strip() else line for line in text.split('\n'))


def library_block():
    parts = ['    property var %s: (function () {' % LIB]
    exports = []
    for prefix, fname in MODULES:
        src = module_source(os.path.join(PLUGIN, fname))
        names = exported_names(src)
        parts.append(indent('// ---- %s ----' % fname, 8))
        parts.append(indent(src, 8))
        table = ', '.join('%s: %s' % (n, n) for n in names)
        parts.append(indent('var %s = { %s };' % (prefix, table), 8))
        exports.append('%s: %s' % (prefix, prefix))
    parts.append(indent('return { %s };' % ', '.join(exports), 8))
    parts.append('    })()')
    return '\n'.join(parts)


def build():
    lib = library_block()
    os.makedirs(DIST, exist_ok=True)
    written = []
    for src_name, out_name in QMLS:
        text = open(os.path.join(PLUGIN, src_name)).read()
        text = re.sub(r'^\s*import\s+"(analyse|strings)\.js"\s+as\s+\w+\s*\n', '', text, flags=re.M)
        # qualify module calls before the library is pasted in, so the regex
        # can't reach into the inlined sources
        for prefix, _ in MODULES:
            text = re.sub(r'(?<![\w.])%s\.([A-Za-z_]\w*)' % prefix,
                          lambda m, p=prefix: '%s.%s.%s' % (LIB, p, m.group(1)), text)
        text = re.sub(r'(MuseScore\s*\{\n)', lambda m: m.group(1) + lib + '\n\n', text, count=1)
        header = ('// Playability Checker — generated by bundle.py, do not edit.\n'
                  '// Sources live in plugin/. Self-contained: no companion .js files needed.\n')
        path = os.path.join(DIST, out_name)
        open(path, 'w').write(header + text)
        written.append(path)
    return written


if __name__ == '__main__':
    for p in build():
        print('wrote %s (%d bytes)' % (p, os.path.getsize(p)))
